public void AutoNumerate()
		{
			Document doc = this.Application.ActiveUIDocument.Document;
			ViewSchedule vs = this.ActiveView as ViewSchedule;
			TableData tData = vs.GetTableData();
			TableSectionData tsDada = tData.GetSectionData(SectionType.Body);
			int startIndex = 1; //Стартовый значение для номера
			using (TransactionGroup tGroup = new TransactionGroup(doc,"Автонумерация спецификации: "+vs.Name)) {
				tGroup.Start();
				for (int rInd = 0; rInd < tsDada.NumberOfRows; rInd++) {
					List<Element> elementsOnRow = GetElementsOnRow(doc,vs,rInd);
					if (null != elementsOnRow) {
						SetNum(doc,startIndex++,elementsOnRow);
					}
				}
				tGroup.Assimilate();
			}
		}
		
		private void SetNum(Document doc, int num, List<Element> elements)
		{
			using (Transaction tr = new Transaction(doc,"Задание номера позиции элементам")) {
				tr.Start();
				foreach (Element curElement in elements) {
					curElement.LookupParameter("Комментарии").Set(num.ToString()); // Заполнение параметра Комментарии
					//curElement.get_Parameter(new Guid("AE8FF999-1F22-4ED7-AD33-61503D85F0F4")).Set(num.ToString()); // Заполнение общего параметра ADSK_Позиция
				}
				tr.Commit();
			}
		}
		
		private List<Element> GetElementsOnRow(Document doc, ViewSchedule vs, int rowNumber)
		{
			TableData tableData =  vs.GetTableData();
			TableSectionData tableSectionData = tableData.GetSectionData(SectionType.Body);
			List<ElementId> elemIds = new FilteredElementCollector(doc,vs.Id)
				.ToElementIds()
				.ToList();
			List<Element> elementsOnRow = new List<Element>();
			List<ElementId> remainingElementsIds = null;

			using(Transaction t = new Transaction(doc,"Empty"))
			{
				t.Start();
				using (SubTransaction st = new SubTransaction(doc))
				{
					st.Start();
					try {
						tableSectionData.RemoveRow(rowNumber);
					} catch (Exception) {
						return null;
					}
					st.Commit();
				}
				remainingElementsIds = new FilteredElementCollector(doc,vs.Id)
					.ToElementIds()
					.ToList();
				t.RollBack();
			}
			foreach(ElementId id in elemIds)
			{
				if(remainingElementsIds.Contains(id)) continue;
				elementsOnRow.Add(doc.GetElement(id));
			}
			return elementsOnRow;
		}
